name: Generate README stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate stats cards
        uses: readme-tools/github-readme-stats-action@v1
        with:
          username: denysefreitas
          theme: radical
          output_path: profile
          cards: |
            stats
            top-langs

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "chore(readme): update stats cards" || exit 0
          git push
